### ISSUE TITLE
Can we remove jquery library from dependences in bower.json?

### ISSUE THREAD

**Issue by tony0918** [igorlino/angular-annotorious#3]
Haven't got a sight at any usage here. And we can include jquery from CDN for test. Right?
Thanks.

**Comment by igorlino** [comment]
yes true, will check.

**Comment by igorlino** [comment]
The annotarious plugin works with the DOM, and most likely you would like to create/use an storage provider. See (https://github.com/igorlino/angular-annotorious/issues/4)

So its fine to use from the latest CDN.
