### ISSUE TITLE
1.0.4 on npm?

### ISSUE THREAD

**Issue by sarsenault** [igorlino/angular-annotorious#5]
Any chance of getting 1.0.4 pushed to npm as well? I need to use the setProperties function for an existing app that I am transitioning from Bower to npm for the front-end, yet only 1.0.1 is available on npm. If it could get pushed, that would be greatly appreciated!

Thanks!

**Comment by sarsenault** [comment]
I see now that this is likely related to annotorious itself not being available past 0.6.3-a on npm, rather than angular-annotorious...

**Comment by igorlino** [comment]
Hi,

I have published the latest versions in NPM.
 Hope that helps ;)
